Year2/Web Application Development/Task2/routes/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("routes/", include("routes.urls", namespace="routes")),
    path("api/", include("routes.api_urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Year2/Web Application Development/Task2/routes/routes/urls.py
app_name = "routes"

from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("my-routes/", views.my_routes, name="my_routes"),
    path("route/<int:pk>/", views.route_detail, name="route_detail"),
    path("new-route/", views.route_detail, name="new_route"),
    path("route/<int:pk>/delete/", views.route_delete, name="route_delete"),
    path("point/<int:pk>/delete/", views.point_delete, name="point_delete"),
    path("gameboard/", views.gameboard, name="gameboard"),
    path("gameboard_save/", views.gameboard_save, name="gameboard_save"),
    path("my_gameboards/", views.my_gameboards, name="my_gameboards"),
    path("gameboard/<int:pk>/", views.gameboard, name="gameboard"),
    path("gameboard/<int:pk>/delete/", views.gameboard_delete, name="gameboard_delete"),
    path("my_paths/", views.my_paths, name="my_paths"),
    path("path_entry/<int:pk>/", views.path_entry, name="path_entry"),
    path("path/<int:pk>/", views.path, name="path"),
    path("path_save/<int:pk>/", views.path_save, name="path_save"),
    path("sse/notifications/", views.sse_notifications, name="sse_notifications")
]

Year2/Web Application Development/Task2/routes/routes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.postgres.fields import JSONField

class BackgroundImage(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    image = models.ImageField(upload_to="backgrounds/", null=False, blank=False)

    class Meta:
        verbose_name = "Background Image"
        verbose_name_plural = "Background Images"

    def __str__(self):
        return self.name
    

class Route(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="routes", null=False)
    background = models.ForeignKey(BackgroundImage, on_delete=models.CASCADE, related_name="routes", null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} (by {self.user.username})'
    

class RoutePoint(models.Model):
    route = models.ForeignKey(Route, on_delete=models.CASCADE, related_name="points", null=False)
    x = models.FloatField(null=False, blank=False)
    y = models.FloatField(null=False, blank=False)
    order = models.IntegerField(default=0, null=False, blank=False)

    class Meta:
        verbose_name = "Route Point"
        verbose_name_plural = "Route Points"
        ordering = ['order']
        unique_together = ('route', 'order')

    def clean(self):
        if not (0 <= self.x <= 100):
            raise ValidationError("X coordinate must be between 0 and 100.")
        
        if not (0 <= self.y <= 100):
            raise ValidationError("Y coordinate must be between 0 and 100.")

    def __str__(self):
        return f'Point {self.order} of {self.route.name}: ({self.x}, {self.y})'
    

class GameBoard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="game_boards", null=False)
    title = models.CharField(max_length=100,  null=False, blank=False)
    rows = models.IntegerField(null=False, blank=False)
    cols = models.IntegerField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    dots = models.JSONField()

    def __str__(self):
        return f'{self.title} (by {self.user.username})'
    

class Path(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    board = models.ForeignKey(GameBoard, on_delete=models.CASCADE, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    path = models.JSONField()

Year2/Web Application Development/Task2/routes/routes/forms.py
from django import forms
from .models import Route, RoutePoint


class RouteForm(forms.ModelForm):
    class Meta:
        model = Route
        fields = ["name", "background"]


class RoutePointForm(forms.ModelForm):
    class Meta:
        model = RoutePoint
        fields = ["x", "y"]

        def clean_x(self):
            x = self.cleaned_data["x"]
            if not (0 <= x <= 100):
                raise forms.ValidationError("X coordinate must be between 0 and 100.")
            return x
        
        def clean_y(self):
            y = self.cleaned_data["y"]
            if not (0 <= y <= 100):
                raise forms.ValidationError("Y must be between 0 and 100.")
            return y

Year2/Web Application Development/Task2/routes/routes/admin.py
from django.contrib import admin
from django.contrib.sites.models import Site
from django.contrib.auth.models import Group
from rest_framework.authtoken.models import Token
from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount, SocialApp, SocialToken

from .models import BackgroundImage, Route, RoutePoint, GameBoard, Path

admin.site.unregister(SocialAccount)
admin.site.unregister(SocialApp)
admin.site.unregister(SocialToken)
admin.site.unregister(EmailAddress)
admin.site.unregister(Site)
admin.site.unregister(Group)

@admin.register(BackgroundImage)
class BackgroundImageAdmin(admin.ModelAdmin):
    list_display = ('name', 'image', 'pk')


@admin.register(Route)
class RouteAdmin(admin.ModelAdmin):
    list_display = ('name', 'user', 'background', 'created_at', 'pk')
    search_fields = ('name', 'user__username', 'pk')

    def custom_method(self, obj):
        return f"Custom Value for {obj.name}"


@admin.register(RoutePoint)
class RoutePointAdmin(admin.ModelAdmin):
    list_display = ('route', 'x', 'y', 'order', 'pk')
    search_fields = ('route__name','pk')

@admin.register(GameBoard)
class GameBoardAdmin(admin.ModelAdmin):
    list_display = ('title', 'user', 'rows', 'cols', 'created_at', 'dots', 'pk')
    search_fields = ('title', 'user__username', 'pk')

@admin.register(Path)
class PathAdmin(admin.ModelAdmin):
    list_display = ('board', 'user', 'pk')
    search_fields = ('board', 'user', 'pk')

Year2/Web Application Development/Task2/routes/routes/api_urls.py
from rest_framework.routers import DefaultRouter
from rest_framework.authentication import TokenAuthentication
from rest_framework import permissions
from rest_framework_nested import routers
from django.urls import path, include
from dj_rest_auth.views import LoginView, LogoutView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from .views import RouteViewSet, RoutePointViewSet, CustomRegisterView

router = DefaultRouter()
router.register('routes', RouteViewSet, basename='route')

routes_router = routers.DefaultRouter()
routes_router.register('routes', RouteViewSet, basename='route')


points_router = routers.NestedDefaultRouter(routes_router, 'routes', lookup='route')
points_router.register('points', RoutePointViewSet, basename='route-points')

schema_view = get_schema_view(
    openapi.Info(
        title='Route API',
        default_version='v1',
        description='API for managing routes and points.',
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    authentication_classes=[TokenAuthentication]
)

urlpatterns = [
    path('', include(routes_router.urls)),
    path('', include(points_router.urls)),
    path('auth/login/', LoginView.as_view(), name='auth_login'),
    path('auth/logout/', LogoutView.as_view(), name='auth_logout'),
    path('auth/register/', CustomRegisterView.as_view(), name='auth_register'),

    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),

    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

Year2/Web Application Development/Task2/routes/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "routes"

    def ready(self):
        import routes.signals

Year2/Web Application Development/Task2/routes/routes/serializers.py
from rest_framework import serializers
from dj_rest_auth.registration.serializers import RegisterSerializer
from drf_yasg.utils import swagger_serializer_method
from django.contrib.auth import get_user_model

from .models import Route, RoutePoint, BackgroundImage

class RoutePointSerializer(serializers.ModelSerializer):
    class Meta:
        model = RoutePoint
        fields = ['id', 'x', 'y', 'order']

    def validate_x(self, value):
        if not (0 <= value <= 100):
            raise serializers.ValidationError("X coordinate must be between 0 and 100.")
        return value

    def validate_y(self, value):
        if not (0 <= value <= 100):
            raise serializers.ValidationError("Y coordinate must be between 0 and 100.")
        return value
    
    def validate_order(self, value):
        if value < 0:
            raise serializers.ValidationError("Order must be zero or a positive integer.")
        return value


class RouteSerializer(serializers.ModelSerializer):
    points = RoutePointSerializer(many=True, read_only=True)
    background = serializers.PrimaryKeyRelatedField(queryset=BackgroundImage.objects.all(), write_only=True)
    background_image = serializers.ImageField(source='background.image', read_only=True)

    class Meta:
        model = Route
        fields = ['id', 'name', 'background', 'background_image', 'created_at', 'points']



class CustomRegisterSerializer(RegisterSerializer):
    class Meta:
        fields = ['username', 'password']
        

    email = None
    password1 = None
    password2 = None

    password = serializers.CharField(write_only=True, required=True)

    def validate(self, data):
        if 'password' in data:
            password = data.get('password')
            if not password:
                raise serializers.ValidationError("Password is required.")

        return data

    def save(self, request):
        user = get_user_model().objects.create_user(
            username=self.validated_data['username'],
            password=self.validated_data['password'],
        )
        return user
    
    @swagger_serializer_method(serializer_or_field=serializers.CharField)
    def get_swagger_fields(cls):
        return {
            'username': serializers.CharField(required=True),
            'password': serializers.CharField(write_only=True, required=True)
        }

Year2/Web Application Development/Task2/routes/routes/signals.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from threading import Lock

from .models import GameBoard, Path
from .views import events, current_id

lock = Lock()

@receiver(post_save, sender=GameBoard)
def board_created(sender, instance, created, **kwargs):
    if created:
        with lock:
            current_id[0] += 1
            events.append({
                "type": "newBoard",
                "data": {
                    "board_id": instance.pk,
                    "board_name": instance.title,
                    "creator_username": instance.user.username if instance.user else "unknown"
                }
            })


@receiver(post_save, sender=Path)
def path_created(sender, instance, created, **kwargs):
    if created:
        with lock:
            current_id[0] += 1
            events.append({
                "type": "newPath",
                "data": {
                    "path_id": instance.pk,
                    "board_id": instance.board.pk,
                    "board_name": instance.board.title,
                    "user_username": instance.user.username if instance.user else "unknown"
                }
            })

Year2/Web Application Development/Task2/routes/routes/templates/routes/my_routes.html
{% load static %}
<body>
<div class="main">
<div class="header"><h2>Your Routes</h2></div>
<form>
<ul>
    {% for route in routes %}
        <li>
            <a href="{% url 'routes:route_detail' route.pk %}">
                {{ route.name }}
            </a>
        </li>
    {% empty %}
        <li> No routes found </li>
    {% endfor %}
</ul>
</form>
<div id="footer">
    <button onclick="location.href='{% url 'routes:index' %}'">Back to Index</button>
    <button onclick="location.href='{% url 'routes:new_route' %}'">Create Route</button>
</div>
</div>
</body>
<script src="{% static 'js/dist/sse.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

Year2/Web Application Development/Task2/routes/routes/templates/routes/point_delete.html
{% load static %}
<body>
<div class="main">
<div class="header"><h2>Are you sure you want to delete this board?</h2></div>
<form method="post">
<p>Route: {{ point.route }}</p>
<p>Order: {{ point.order }}</p>
<p>Coordinates: {{ point.x }}, {{ point.y }}</p>

    {% csrf_token %}
    <button type="submit">Delete</button>
<div id="footer">
    <button type="button" onclick="location.href='{% url "routes:route_detail" point.route.pk %}'">
    Cancel
    </button>
</div>
</form>
</div>
</body>
<script src="{% static 'js/dist/sse.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

Year2/Web Application Development/Task2/routes/routes/templates/routes/route_delete.html
{% load static %}
<body>
<div class="main">
<div class="header"><h2>Are you sure you want to delete this route?</h2></div>
<form method="post">
<p>Title: {{ route.name }}</p>
<p>Created at: {{ route.created_at }}</p>

    {% csrf_token %}
    <button type="submit">Delete</button>
<div id="footer">
    <button type="button" onclick="location.href='{% url "routes:route_detail" route.pk %}'">
    Cancel
    </button>
</div>
</form>
</div>
</body>
<script src="{% static 'js/dist/sse.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

Year2/Web Application Development/Task2/routes/routes/templates/routes/route_detail.html
{% load custom_filters %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>
<div class="main">
{% if route %}
    <div class="header" style="z-index: 100;"><h2>{{ route.name }}</h2></div>
    <div id="route-meta">
        <p>Created: {{ route.created_at }}</p>
        <p>Background: {{ route.background }}</p>
    </div>

    <form method="post" style="margin-top: 50px">
    <h3 class="header">Add Point</h3>
        {% csrf_token %}
        {{ point_form.as_p }}
        <button type="submit" name="add_point">Add Point</button>
    </form>

    <div id="image-container" style="align-self: center; position: relative; width: 75%">
        <img src="{{ route.background.image.url }}" alt="bg" style="width: 100%; display: block;" id="route-image">

        {% for point in route.points.all %}
            <div class="point"
                style="position: absolute;
                        top: {{ point.y }}%;
                        left: {{ point.x }}%;
                        z-index: 1;
                        transform: translate(-50%, -50%);
                        width: 10px;
                        height: 10px;
                        background: red;
                        border-radius: 50%;"
                {% if forloop.last %}
                    id="last-point"
                    data-x="{{ point.x }}"
                    data-y="{{ point.y }}"
                {% endif %}
            >
            </div>
        {% endfor %}

        <svg style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"
             viewBox="0 0 100 100" preserveAspectRatio="none" id='route-svg'>

            {% if route.points.all|length > 1%}
                {% for point in route.points.all %}
                    {% with next_point=route.points.all|get_item:forloop.counter %}
                    {% if next_point %}
                        <line x1="{{ point.x }}" y1="{{ point.y }}"
                            x2="{{ next_point.x }}" y2="{{ next_point.y }}"
                            stroke="blue" stroke-width="0.5" />
                    {% endif %}
                    {% endwith %}
                {% endfor %}
            {% endif%}
        </svg>
    </div>

    <form>
    <h3 class="header">Route Points</h3>
    <ul>
      {% for point in route.points.all %}
        <li class="point-item" data-x="{{ point.x }}" data-y="{{ point.y }}">
          ({{ point.x }}, {{ point.y }})
          <button onclick="location.href='{% url 'routes:point_delete' point.pk %}'" type="button">Delete</button>
        </li>
      {% endfor %}
    </ul>
    </form>
    <div id="footer">
    <button onclick="location.href='{% url 'routes:route_delete' route.pk %}'">Delete Route</button>

    <button onclick="location.href='{% url 'routes:my_routes' %}'">Back to Your Routes</button>
    </div>
{% else %}
    <div class="header"><h2> Create New Route </h2></div>
    <form method="post">
        {% csrf_token %}
        {{ route_form.as_p }}
        <button type="submit" name="save_route">Create Route</button>
    </form>
    <div class="footer" style="align-self: center">
    <button onclick="location.href='{% url 'routes:my_routes' %}'">Cancel</button>
    </div>
{% endif %}
</div>
</body>
<script src="{% static 'js/dist/add_point.js' %}"></script>
<script src="{% static 'js/dist/highlight.js' %}"></script>
<script src="{% static 'js/dist/sse.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/styles.css' %}">